---
- name: Copy installarr.sh to home directory
  ansible.builtin.copy:
    src: installarr.sh
    dest: "/root/"
    mode: '0744'

- name: Run installarr.sh with responses
  ansible.builtin.shell: "printf '2\nprowlarr\nmedia\n1\nY' | bash /root/installarr.sh"

- name: Get service facts
  ansible.builtin.service_facts:

- name: proxy prowlarr if nginx is installed
  block:
  - name: Configure NGINX for Radarr
    ansible.builtin.copy:
      src: proxy-prowlarr.conf
      dest: /etc/nginx/proxies/
      mode: "0644"
      owner: root
      group: root

  - name: Modify UrlBase in prowlarr config
    ansible.builtin.lineinfile:
      path: /var/lib/prowlarr/config.xml
      regexp: "^  <UrlBase>.*$"
      line: "  <UrlBase>/prowlarr</UrlBase>"
      create: true
      mode: '0644'
      owner: prowlarr
      group: media

  - name: restart nginx and prowlarr
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - nginx
      - prowlarr
  when: ansible_facts.services['nginx.service'] is defined